// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa3tEYwUmwQYuHEzJvbiHrkPm7s8haL2k',
    appId: '1:757056796917:web:82f40c63aff1e011d46dbc',
    messagingSenderId: '757056796917',
    projectId: 'motchiy-todo',
    authDomain: 'motchiy-todo.firebaseapp.com',
    storageBucket: 'motchiy-todo.firebasestorage.app',
    measurementId: 'G-1Y95X9LGGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlN9LZEwIjYapwf6r4YASqDon_BO-IUc',
    appId: '1:757056796917:android:86d5ea1d377b6802d46dbc',
    messagingSenderId: '757056796917',
    projectId: 'motchiy-todo',
    storageBucket: 'motchiy-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjsJ7mq8CsVyFVhuAh0AQKvNwwk1EJig',
    appId: '1:757056796917:ios:f0426eb3bc050beed46dbc',
    messagingSenderId: '757056796917',
    projectId: 'motchiy-todo',
    storageBucket: 'motchiy-todo.firebasestorage.app',
    iosBundleId: 'com.example.motchiyTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjsJ7mq8CsVyFVhuAh0AQKvNwwk1EJig',
    appId: '1:757056796917:ios:f0426eb3bc050beed46dbc',
    messagingSenderId: '757056796917',
    projectId: 'motchiy-todo',
    storageBucket: 'motchiy-todo.firebasestorage.app',
    iosBundleId: 'com.example.motchiyTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa3tEYwUmwQYuHEzJvbiHrkPm7s8haL2k',
    appId: '1:757056796917:web:cad609eae9799f91d46dbc',
    messagingSenderId: '757056796917',
    projectId: 'motchiy-todo',
    authDomain: 'motchiy-todo.firebaseapp.com',
    storageBucket: 'motchiy-todo.firebasestorage.app',
    measurementId: 'G-VGYVVGQBRY',
  );
}
